# Generated by Django 4.2.1 on 2023-06-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_producer'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='producers',
            field=models.ManyToManyField(to='films.producer'),
        ),
    ]
