# Generated by Django 4.2.1 on 2023-06-11 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='created_at',
            new_name='date_joined',
        ),
        migrations.RemoveField(
            model_name='student',
            name='temperature',
        ),
    ]
